#! /bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-scale ~/img/bg4.jpg

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config pointer_modifier	mod4

#mod4 = super

bspc config normal_border_color "#0A1F32"
bspc config active_border_color "#2D384A"
bspc config focused_border_color "#344756"

$HOME/.config/polybar/launch.sh


